set $ws1 1:comm
set $ws2 2:work
set $ws3 3:browser
set $ws8 8:pikvm

bindsym --no-warn $mod+1 workspace number $ws1
bindsym --no-warn $mod+2 workspace number $ws2
bindsym --no-warn $mod+3 workspace number $ws3
bindsym --no-warn $mod+8 workspace number $ws8
bindsym --no-warn $mod+9 workspace number $ws9

bindsym --no-warn $mod+Shift+1 move container to workspace number $ws1
bindsym --no-warn $mod+Shift+2 move container to workspace number $ws2
bindsym --no-warn $mod+Shift+3 move container to workspace number $ws3
bindsym --no-warn $mod+Shift+8 move container to workspace number $ws8
bindsym --no-warn $mod+Shift+9 move container to workspace number $ws9

assign [app_id="bluebubbles"]    workspace number $ws1
assign [app_id="com.slack.Slack"] workspace number $ws1